# Generated by Django 4.0 on 2023-06-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='postId',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
    ]
